
import Clases.Alumno;
import Clases.Materia;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author martinleiza
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioInscripcion
     */
    public FormularioInscripcion() {
        initComponents();
        
        //Cargar el comboBox
        cargarCombosB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_formularioInscripcion = new javax.swing.JLabel();
        lbl_materia = new javax.swing.JLabel();
        cbo_materia = new javax.swing.JComboBox<>();
        lbl_alumno = new javax.swing.JLabel();
        cbo_alumno = new javax.swing.JComboBox<>();
        btn_inscribir = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Inscripcio a Materia");

        lbl_formularioInscripcion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_formularioInscripcion.setText("Formulario de Inscripción");

        lbl_materia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_materia.setText("Elija una Materia:");

        cbo_materia.setSelectedIndex(-1);
        cbo_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_materiaActionPerformed(evt);
            }
        });

        lbl_alumno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_alumno.setText("Elija un Alumno:");

        cbo_alumno.setSelectedIndex(-1);

        btn_inscribir.setText("Inscribir");
        btn_inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscribirActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_inscribir)
                .addGap(18, 18, 18)
                .addComponent(btn_salir)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_materia)
                            .addComponent(lbl_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbo_materia, 0, 211, Short.MAX_VALUE)
                            .addComponent(cbo_alumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lbl_formularioInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_formularioInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_materia)
                    .addComponent(cbo_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbl_alumno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cbo_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inscribir)
                    .addComponent(btn_salir))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_materiaActionPerformed

    private void btn_inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscribirActionPerformed
        // TODO add your handling code here:
        Alumno alumno = (Alumno) cbo_alumno.getSelectedItem();
        Materia materia = (Materia) cbo_materia.getSelectedItem();

        if (alumno == null || materia == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccioná alumno y materia.");
            return;
        }

        alumno.agregarMateria(materia);
    }//GEN-LAST:event_btn_inscribirActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed


    private void cargarCombosB() {
        cbo_materia.removeAllItems();
        cbo_alumno.removeAllItems();

        for (Alumno a : Colegio.alumnos) {
            cbo_alumno.addItem(a);
        }
        for (Materia m : Colegio.materias) {
            cbo_materia.addItem(m);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inscribir;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<Alumno> cbo_alumno;
    private javax.swing.JComboBox<Materia> cbo_materia;
    private javax.swing.JLabel lbl_alumno;
    private javax.swing.JLabel lbl_formularioInscripcion;
    private javax.swing.JLabel lbl_materia;
    // End of variables declaration//GEN-END:variables
}
