
import Clases.Materia;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class FormularioMateria extends javax.swing.JInternalFrame {
    
    //Usamos el HashSet compartido de Colegio
    //public static final Set<Materia>materias = new HashSet<>();
        
    /**
     * Creates new form FormularioMateria
     */
    public FormularioMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JtCodigo = new javax.swing.JTextField();
        JtNombre = new javax.swing.JTextField();
        JtAño = new javax.swing.JTextField();
        Jbguardar = new javax.swing.JButton();
        Jbnuevo = new javax.swing.JButton();
        Jbsalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar Materia");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Formulario de Materia.");

        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Codigo Materia:");

        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Nombre Materia:");

        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Año al que pertenece:");

        Jbguardar.setForeground(new java.awt.Color(0, 153, 204));
        Jbguardar.setText("Guardar");
        Jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbguardarActionPerformed(evt);
            }
        });

        Jbnuevo.setForeground(new java.awt.Color(0, 153, 204));
        Jbnuevo.setText("Nuevo");
        Jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbnuevoActionPerformed(evt);
            }
        });

        Jbsalir.setForeground(new java.awt.Color(0, 153, 204));
        Jbsalir.setText("Salir");
        Jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Jbguardar)
                .addGap(18, 18, 18)
                .addComponent(Jbnuevo)
                .addGap(39, 39, 39)
                .addComponent(Jbsalir)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbsalir)
                    .addComponent(Jbnuevo)
                    .addComponent(Jbguardar))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbnuevoActionPerformed
        // TODO add your handling code here:
        JtCodigo.setText("");
        JtAño.setText("");
        JtNombre.setText("");
    }//GEN-LAST:event_JbnuevoActionPerformed

    private void JbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JbsalirActionPerformed

    private void JbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbguardarActionPerformed
        // TODO add your handling code here:
     try {   
       int codigo = Integer.parseInt(JtCodigo.getText());
       String nombre = JtNombre.getText();
       int anio = Integer.parseInt(JtAño.getText());
       
       
      if (nombre.isEmpty()) {
          JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
      }
      Materia matilda = new Materia (codigo, nombre, anio);
      
       if(!Colegio.materias.add(matilda)){
            JOptionPane.showMessageDialog(this, "Ya existe una materia con ese codigo", "Duplicado",JOptionPane.WARNING_MESSAGE);
       
            return;
       }
       JOptionPane.showMessageDialog(this, "Materia " + nombre + " de codigo " + codigo + "  .Guardado Correctamente");
     }catch (NumberFormatException e){
         JOptionPane.showMessageDialog(this, "Debe ingresar un caracter numerico en codigo y año", "Error", JOptionPane.ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_JbguardarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbguardar;
    private javax.swing.JButton Jbnuevo;
    private javax.swing.JButton Jbsalir;
    private javax.swing.JTextField JtAño;
    private javax.swing.JTextField JtCodigo;
    private javax.swing.JTextField JtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
