
import Clases.Materia;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arceb
 */
public class jFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jFramePrincipal
     */
    public jFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdEscritorio = new javax.swing.JDesktopPane();
        jBarraPrincipal = new javax.swing.JMenuBar();
        jAlumno = new javax.swing.JMenu();
        jmAgregarAlum = new javax.swing.JMenuItem();
        jMateria = new javax.swing.JMenu();
        AgregarMateria = new javax.swing.JMenuItem();
        jRegistro = new javax.swing.JMenu();
        jMenuFormInscripcion = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdEscritorioLayout = new javax.swing.GroupLayout(jdEscritorio);
        jdEscritorio.setLayout(jdEscritorioLayout);
        jdEscritorioLayout.setHorizontalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        jdEscritorioLayout.setVerticalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jAlumno.setText("Alumno");

        jmAgregarAlum.setText("Formulario de Alumnos");
        jmAgregarAlum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAgregarAlumMouseClicked(evt);
            }
        });
        jmAgregarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarAlumActionPerformed(evt);
            }
        });
        jAlumno.add(jmAgregarAlum);

        jBarraPrincipal.add(jAlumno);

        jMateria.setText("Materia");

        AgregarMateria.setText("Agregar Materia:");
        AgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMateriaActionPerformed(evt);
            }
        });
        jMateria.add(AgregarMateria);

        jBarraPrincipal.add(jMateria);

        jRegistro.setText("Inscripcion");

        jMenuFormInscripcion.setText("Formulario de Inscripcion");
        jMenuFormInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFormInscripcionActionPerformed(evt);
            }
        });
        jRegistro.add(jMenuFormInscripcion);

        jBarraPrincipal.add(jRegistro);

        jSalir.setText("Salir");
        jBarraPrincipal.add(jSalir);

        setJMenuBar(jBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAgregarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarAlumActionPerformed
        // TODO add your handling code here:
        FormularioAlumno agregar = new FormularioAlumno();
        agregar.setSize(450, 350);
        agregar.setVisible(true);
        jdEscritorio.add(agregar);
    }//GEN-LAST:event_jmAgregarAlumActionPerformed

    private void jmAgregarAlumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAgregarAlumMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jmAgregarAlumMouseClicked

    private void AgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMateriaActionPerformed
        FormularioMateria agregar2 = new FormularioMateria();
        agregar2.setVisible(true);
        agregar2.setSize(450,350);
        jdEscritorio.add(agregar2);
    }//GEN-LAST:event_AgregarMateriaActionPerformed

    private void jMenuFormInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFormInscripcionActionPerformed
        FormularioInscripcion agregar3 = new FormularioInscripcion();
        agregar3.setVisible(true);
        agregar3.setSize(450,350);
        jdEscritorio.add(agregar3);

    }//GEN-LAST:event_jMenuFormInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFramePrincipal().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarMateria;
    private javax.swing.JMenu jAlumno;
    private javax.swing.JMenuBar jBarraPrincipal;
    private javax.swing.JMenu jMateria;
    private javax.swing.JMenuItem jMenuFormInscripcion;
    private javax.swing.JMenu jRegistro;
    private javax.swing.JMenu jSalir;
    private javax.swing.JDesktopPane jdEscritorio;
    private javax.swing.JMenuItem jmAgregarAlum;
    // End of variables declaration//GEN-END:variables
}
